# Generated by Django 3.2.9 on 2022-01-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Pizza_name', models.CharField(max_length=100)),
                ('Pizza_desc', models.TextField()),
                ('Pizza_price', models.FloatField()),
                ('image_url', models.URLField(default='')),
            ],
        ),
    ]
